name: helping_hand
description: An app to help the people in need in this pandemic

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  introduction_screen: ^1.0.8
  cached_network_image: ^2.0.0
  sleek_circular_slider: ^1.1.0
  google_maps_flutter: ^0.5.11
  location: ^2.5.4
  flutter_polyline_points: ^0.1.0
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.0+1
  google_sign_in: ^4.4.1
  geolocator: ^5.2.0
  intl_phone_number_input: ^0.3.0
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.17.4
  gender_selector: ^1.0.6
  curved_navigation_bar: ^0.3.2
  modal_progress_hud: ^0.1.3
  provider:
  image_picker: ^0.6.0+2
  rflutter_alert: ^1.0.3
  uuid: ^2.0.0
  firebase_storage: ^3.1.1
  url_launcher: ^5.4.5
  image: ^2.0.7
  shared_preferences: ^0.5.7
  animated_text_kit: ^2.0.0
  firebase_messaging: ^6.0.13
  get_it: ^4.0.1
  flutter_facebook_login: ^3.0.0
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf 

  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/

