name: helping_hand
description: An app to help the people in need in this pandemic

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  introduction_screen: ^1.0.8
  cached_network_image: ^2.0.0
  sleek_circular_slider: ^1.1.0
  google_maps_flutter: ^0.5.24+1
  location: ^2.5.4
  flutter_polyline_points: ^0.1.0
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.0+1
  google_sign_in: ^4.4.1
  geolocator: ^5.2.0
  intl_phone_number_input: ^0.3.0
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.17.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf 

  uses-material-design: true
  
  assets:
    - assets/images/

